baseURL = "https://aaronzhang1607.github.io"
languageCode = "en-us"
title = "Yajie Zhang website"
theme = "researcher"
enableEmoji = true

disableKinds = ["taxonomy", "term"]

[params]
    author = "Yajie Zhang"
    description = "Research Assistant @ WangLab (CIBR) · Hibernation"
    [params.style]  # appearance options
        fontFamily = "Inconsolata"
        fontSize = "14pt"
        pageWidth = "750px"
        colorBlack = "#222222"
        colorRed = "#dc3545"
    [[params.socialIcons]]
        icon = "fab fa-github"
        title = "GitHub"
        url = "https://github.com/aaronzhang1607"

[menu]
    [[menu.main]]
        name = "About"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Posts"
        url = "/post/"
        weight = 2

[markup.goldmark.renderer]
    unsafe = true  # allow raw HTML in markdown files
